@startuml

' Tittel og bunntekst for diagrammet
title Eksempel-diagram
footer Undertekst A

' Klassedefinisjoner med attributter
class Folk {
    -Navn : string
    +Fødselsår : int
}
class Sykkel
class Tastatur
class Datamaskin {
    +Svenskeknapp : boolean
}

' Relasjoner mellom klasser
Folk <-- Datamaskin : bruker
Folk <-- Sykkel : eier
Tastatur --o Datamaskin : består av

@enduml