# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/docs/sushi/configuration/                    │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: hl7.fhir.no.nlk-test
canonical: http://hl7.no/fhir/ig/nlk-test
url: http://hl7.no/fhir/ig/nlk-test
name: NlkTest
title: "Norwegian Laboratory Codebook (NLK) - FHIR Implementation Guide"
description: "FHIR Implementation Guide for the Norwegian Laboratory Codebook (Norsk Laboratoriekodeverk). This IG provides a comprehensive CodeSystem with 11,391 laboratory codes covering all aspects of Norwegian laboratory medicine across six major medical domains."
status: draft
version: 0.1.0
fhirVersion: 4.0.1
copyrightYear: 2025+
releaseLabel: ci-build
experimental: true
date: 2025-09-24
license: CC0-1.0
jurisdiction: urn:iso:std:iso:3166#NO "Norway"
publisher:
  name: Espen
  url: https://github.com/rockphotog/
contact:
  - name: Espen
    telecom:
      - system: url
        value: https://github.com/rockphotog/
dependencies:
  hl7.fhir.no.basis: 2.2.0

# Additional configuration for better IG generation
parameters:
  show-inherited-invariants: false
  usage-stats-opt-out: false
  logging: progress
  
# Template and pages configuration  
template: hl7.fhir.template#current

# Resource configuration
resources:
  CodeSystem/norsk-laboratoriekodeverk:
    name: Norwegian Laboratory Codebook
    description: Complete Norwegian laboratory terminology with 11,391 codes


# Navigation menu for the Implementation Guide
menu:
  Home: index.html
  Background:
    About NLK: background.html
    Implementation Notes: implementation.html
  Artifacts: artifacts.html
  CodeSystem:
    Norwegian Laboratory Codebook: CodeSystem-norsk-laboratoriekodeverk.html
  Downloads: downloads.html
  History: http://hl7.no/fhir/ig/nlk-test/history.html
