# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/docs/sushi/configuration/                    │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: hl7.fhir.no.nlk-test
canonical: http://hl7.no/fhir/ig/nlk-test
url: http://hl7.no/fhir/ig/nlk-test
name: NlkTest
title: "Norwegian Laboratory Codebook (NLK) - FHIR Implementation Guide"
description: "FHIR Implementation Guide for the Norwegian Laboratory Codebook (Norsk Laboratoriekodeverk). This IG provides a comprehensive CodeSystem with 11,391 laboratory codes covering all aspects of Norwegian laboratory medicine across six major medical domains."
status: draft
version: 0.2.1
fhirVersion: 4.0.1
copyrightYear: 2025+
releaseLabel: ci-build
license: "See original NLK licensing terms"
experimental: true
date: 2025-09-24
jurisdiction: urn:iso:std:iso:3166#NO "Norway"
publisher:
  name: Espen
  url: https://github.com/rockphotog/
contact:
  - name: Espen
    telecom:
      - system: url
        value: https://github.com/rockphotog/


# Navigation menu for the Implementation Guide
menu:
  Home: index.html
  Artifacts: artifacts.html
  Architecture: architecture.html
  CodeSystems:
    Basic CodeSystem: CodeSystem-norsk-laboratoriekodeverk.html
#    Medical Genetics CodeSystem: CodeSystem-norsk-laboratoriekodeverk-medical-genetics.html
#    Detailed CodeSystem: CodeSystem-norsk-laboratoriekodeverk-detailed.html
